from lighthouse.util.log import lmsg
from lighthouse.util.misc import iteritems
from lighthouse.util.disassembler import disassembler

#------------------------------------------------------------------------------
# Exception Definitions
#------------------------------------------------------------------------------

class LighthouseError(Exception):
    """
    An error generated by Lighthouse.
    """
    def __init__(self, *args, **kwargs):
        super(LighthouseError, self).__init__(*args, **kwargs)

#------------------------------------------------------------------------------
# Coverage File Exceptions
#------------------------------------------------------------------------------

class CoverageException(LighthouseError):
    """
    A class of errors pertaining to loading & mapping coverage files.
    """
    name = NotImplementedError
    description = NotImplementedError

    def __init__(self, message, filepath):
        super(CoverageException, self).__init__(message)
        self.filepath = filepath

    @property
    def verbose(self):
        return "错误: %s\n\n%s" % (self.name, self.description)

    def __str__(self):
        return self.message + " '%s'" % self.filepath

class CoverageParsingError(CoverageException):
    """
    An error generated by the CoverageReader when all parsers fail.
    """
    name = "PARSE_FAILURE"
    description = \
        "无法解析一个或多个选中的覆盖率文件。\n\n"  \
        "可能原因:\n"                              \
        " - 选中的文件不是覆盖率文件。\n"           \
        " - 覆盖率文件格式错误或无法读取。\n"       \
        " - 当前未安装适用于该文件的解析器。\n\n"   \
        "请查看反汇编器控制台获取更多信息。"

    def __init__(self, filepath, tracebacks):
        super(CoverageParsingError, self).__init__("无法解析覆盖率文件", filepath)
        self.tracebacks = tracebacks

class CoverageMissingError(CoverageException):
    """
    An error generated when no data was extracted from a CoverageFile.
    """
    name = "NO_COVERAGE_ERROR"
    description = \
        "未能从某个选中的文件中提取可用覆盖率数据。\n\n" \
        "可能原因:\n"                                      \
        " - 选择了其他二进制文件的覆盖率文件。\n"           \
        " - 生成当前数据库的可执行文件名称与采集覆盖率时不同。\n" \
        " - DBI 工具没有采集到该二进制文件的任何覆盖率。\n\n" \
        "请查看反汇编器控制台获取更多信息。"

    def __init__(self, filepath):
        super(CoverageMissingError, self).__init__("未从文件中提取到覆盖率", filepath)

class CoverageMappingAbsent(CoverageException):
    """
    A warning generated when coverage data cannot be mapped.
    """
    name = "NO_COVERAGE_MAPPED"
    description = \
        "一个或多个已加载的覆盖率文件没有可见的映射数据。\n\n" \
        "可能原因:\n"                                           \
        " - 覆盖率数据没有落在已定义函数范围内。\n"              \
        " - 绝对地址 trace 的镜像基址与当前数据库不同。\n"       \
        " - 覆盖率数据可能损坏或格式异常。\n\n"                  \
        "请查看反汇编器控制台获取更多信息。"

    def __init__(self, coverage):
        super(CoverageMappingAbsent, self).__init__("无法映射覆盖率数据", coverage.filepath)
        self.coverage = coverage

class CoverageMappingSuspicious(CoverageException):
    """
    A warning generated when coverage data does not appear to match the database.
    """
    name = "BAD_COVERAGE_MAPPING"
    description = \
        "一个或多个已加载的覆盖率文件看起来映射异常。\n\n" \
        "可能原因:\n"                                       \
        " - 选择了错误的二进制文件或模块。\n"                \
        " - 覆盖率文件对应的二进制版本与当前打开的数据库不匹配。\n" \
        " - 目标存在自修改代码或异常控制流，例如混淆代码、恶意样本、加壳程序。\n" \
        " - 覆盖率数据可能损坏或格式异常。\n\n"              \
        "这意味着 Lighthouse 显示的覆盖率很可能不正确，不应直接信任。"

    def __init__(self, coverage):
        super(CoverageMappingSuspicious, self).__init__("覆盖率数据看起来映射异常", coverage.filepath)
        self.coverage = coverage

#------------------------------------------------------------------------------
# UI Warnings
#------------------------------------------------------------------------------

def warn_errors(errors, ignore=[]):
    """
    Warn the user of any encountered errors with a messagebox.
    """
    if not errors:
        return

    for error_type, error_list in iteritems(errors):

        #
        # loop through the individual instances/files that caused this error
        # and dump the results to the disassembler console...
        #

        lmsg("-"*50)
        lmsg("报告 %s 的文件:" % error_type.name)
        for error in error_list:
            lmsg(" - %s" % error.filepath)

        # suppress popups for certain errors, if the user has specified such
        if error_type in ignore:
            continue

        #
        # popup a more verbose error messagebox for the user to read regarding
        # this class of error they encountered
        #

        disassembler.warning(error.verbose)

    # done ...
    lmsg("-"*50)
